### ISSUE TITLE
Add OGP and Google Analytics for default

### ISSUE THREAD

**Issue by ixkaito** [ixkaito/frasco#11]

**Comment by S1SYPHOS** [comment]
What about Jekyll's [SEO plugin](https://github.com/jekyll/jekyll-seo-tag), taking care of

> - Page title / description
> - Canonical URL
> - Next and previous URLs on paginated pages
> - JSON-LD Site and post metadata for richer indexing
> - Open graph title, description, site title, and URL (for Facebook, LinkedIn, etc.)
> - Twitter summary card metadata

much easier than doing it manually, very convenient - everything just one gem away :cake: 
While we're at it, how do you like bundler? Then instead of `gem install jekyll` you just do `gem install bundler && bundle install`, and include gems in Gemfile. I don't want to bloat it, just an idea, tell me what you think!

As for GA, that I could send a PR your way ..

**Comment by ixkaito** [comment]
@S1SYPHOS 

Thanks!

> What about Jekyll's SEO plugin

This looks good! I'll take a look at it.

> While we're at it, how do you like bundler?

Yes, if we need more gems than `jekyll`, it'll be better. However, it might have some tricks on `bundle exec`.

**Comment by ixkaito** [comment]
Resolved. We already have OGP, Google Analytics and bundler.
