### ISSUE TITLE
Watch.js not watching for changes in html collections.

### ISSUE THREAD

**Issue by mckeever02** [ixkaito/frasco#37]
Hey,

I just ran into an issue where I couldn't get change to compile for a collection consisting of html pages 
 e.g. _account > index.html. 

I fixed this by adding ` './**/*.html',` to `watch.js`. 

Shouldn't this be added by default or am I missing something?

Great plugin btw!

**Comment by timpotter** [comment]
Yeah, I've ran into the same issue before and have used the same solution as @mckeever02

**Comment by ixkaito** [comment]
@mckeever02 @timpotter Thank you both! You're right. `./**/*.html` is better. On older versions, Browsersync reloads too many times if you set `./**/*.html`. This issue seems to be improved.

I changed `*.html` to `./**/*.html` and removed `config.jekyll.includes + '/**/*', config.jekyll.layouts + '/**/*', config.jekyll.posts + '/**/*'` on v0.8.8.
